---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-flask
  description: Componente de prueba
  tags:
    - service-flask
  annotations:
    github.com/project-slug: JCAL0199/serviceflask
    backstage.io/ci-cd: github-actions
    backstage.io/techdocs-ref: dir:.
    service-flask/version: "1.0.3"
    service-flask/deployed-at: "2025-06-28T14:00Z"
    service-flask/git-commit: "abc123"
  links:
    - url: https://github.com/JCAL0199/serviceflask
      title: Repositorio GitHub
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dispersion-ordinaria-imss
  namespace: flask
  description: Dispersi贸n Ordinaria IMSS
  tags:
    - proceso-negocio
spec:
  type: negocio
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/service-flask
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carga-archivo
  namespace: flask
  description: Dispersi贸n Ordinaria IMSS/Carga Archivo -Edici贸n
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idc
  namespace: flask
  description: Dispersi贸n Ordinaria IMSS/IDC
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
