---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-flask
  description: Componente de prueba
  tags:
    - service-flask
  annotations:
    github.com/project-slug: JCAL0199/serviceflask
    backstage.io/ci-cd: github-actions
    backstage.io/techdocs-ref: dir:.
    version: "1.0.3"
    deployed-at: "2025-06-28T14:00Z"
    git-commit: "abc123"
  links:
    - url: https://github.com/JCAL0199/serviceflask
      title: Repositorio GitHub
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
  system: bdnsar