---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-flask
  description: Componente de prueba
  tags:
    - service-flask
  annotations:
    github.com/project-slug: JCAL0199/serviceflask
    backstage.io/ci-cd: github-actions
    backstage.io/techdocs-ref: dir:.
    version: "1.0.3"
    deployed-at: "2025-06-28T14:00Z"
    git-commit: "abc123"
  links:
    - url: https://github.com/JCAL0199/serviceflask
      title: Repositorio GitHub
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
  system: bdnsar
  dependsOn:
    - component:default/integrationaccountsmovements
    - resource:default/service-flask-db
    - resource:default/service-flask-queue
  consumesApis:
    - user-service-api
  providesApis:
    - service-flask-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-flask-api
  description: API REST para el componente service-flask
  tags:
    - rest
    - flask
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/developers
  system: bdnsar
  definition: |
      openapi: 3.0.0
      info:
        title: Service Flask API
        version: 1.0.3
      paths:
        /ping:
          get:
            summary: Ping endpoint
            responses:
              '200':
                description: Pong
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-service-api
  description: API de gestión de usuarios
spec:
  type: openapi
  lifecycle: production
  owner: group:default/developers
  definition: |
      openapi: 3.0.0
      info:
        title: User Service API
        version: 1.0.0
      paths:
        /users:
          get:
            summary: Obtener usuarios
            responses:
              '200':
                description: Lista de usuarios
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: service-flask-db
  description: Base de datos PostgreSQL usada por service-flask
spec:
  type: database
  owner: group:default/developers
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: service-flask-queue
  description: Cola RabbitMQ para tareas de fondo
spec:
  type: queue
  owner: group:default/developers
  system: bdnsar
