---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-flask
  description: Componente de prueba
  tags:
    - service-flask
  annotations:
    github.com/project-slug: JCAL0199/serviceflask
    backstage.io/ci-cd: github-actions
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dispersion-ordinaria-imss
  description: Dispersión Ordinaria IMSS
  tags:
    - proceso-negocio
spec:
  type: negocio
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/service-flask
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carga-archivo
  description: Dispersión Ordinaria IMSS/Carga Archivo
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idc
  description: Dispersión Ordinaria IMSS/IDC
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss