steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest']

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud deploy releases create release-$(date +%Y%m%d%H%M%S) \
          --project=$PROJECT_ID \
          --region=us-central1 \
          --delivery-pipeline=pipeline-flask \
          --images=flask-image=us-central1-docker.pkg.dev/$PROJECT_ID/flask-repo/flask-image:$COMMIT_SHA

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/flask-repo/flask-image:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY