steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - flask-service
      - --image=us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY