steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/test-cloud-gcp/flask-repo/flask-image:latest']


options:
  logging: CLOUD_LOGGING_ONLY