name: Generar Changelog con Gemini

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Instalar pandoc y LaTeX (para PDF)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Autenticación con Vertex AI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON_IA }}'

      - name: Generar changelog
        run: python changelog_generator.py

      - name: Convertir a PDF
        run: |
          mkdir -p docs/releases
          pandoc CHANGELOG.md -o docs/releases/${{ github.ref_name }}.pdf

      - name: Subir PDF a bucket GCS
        run: |
          gsutil cp docs/releases/${{ github.ref_name }}.pdf gs://bucket-changelog/releases/
