name: Generar documentación con IA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r agent_rag/requirements.txt

      - name: Autenticación con Vertex AI
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON_IA }}'

      - name: Clonar repo objetivo
        run: |
          git clone https://github.com/JCAL0199/serviceflask repo

      - name: Generate and upload docs
        run: python agent_rag/agent.py
