name: Publish TechDocs to GCS (only if changes)

on:
  push:
    branches: [main]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'catalog-info.yaml'

jobs:
  publish-techdocs:
    runs-on: ubuntu-latest

    env:
      ENTITY_NAMESPACE: default
      ENTITY_KIND: component
      ENTITY_NAME: service-flask

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Generate TechDocs locally
        run: |
          mkdir -p /tmp/techdocs
          npx --yes @techdocs/cli build --output-dir site

      - name: Download current docs from GCS
        run: |
          mkdir -p /tmp/gcsdocs
          gsutil -m cp -r gs://${{ secrets.GCP_BUCKET_NAME }}/${{ env.ENTITY_NAMESPACE }}/${{ env.ENTITY_KIND }}/${{ env.ENTITY_NAME }}/* /tmp/gcsdocs || true

      - name: Check for changes in docs
        id: diff_check
        run: |
          diff -qr /tmp/techdocs /tmp/gcsdocs || echo "DIFF_EXISTS=true" >> $GITHUB_ENV

      - name: Upload new docs to GCS (if changed)
        if: env.DIFF_EXISTS == 'true'
        run: |
          echo "Docs changed, uploading to GCS..."
          npx --yes @techdocs/cli publish \
            --publisher-type=googleGcs \
            --storage-name=${{ secrets.GCP_BUCKET_NAME }} \
            --entity=${{ env.ENTITY_NAMESPACE }}/${{ env.ENTITY_KIND }}/${{ env.ENTITY_NAME }}
            --directory=site
        env:
          TECHDOCS_SITEMAP_GENERATOR: 'false'
